pipeline {
    agent any

    stages {
        stage('Build Jar'){
            steps{
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Build Image'){
            steps{
                sh 'docker build -t=zarniaung7/selenium .'
            }
        }
        stage('Push Image'){
        	environment {
        		DOCKER_HUB = credentials('dockerhub-creds');
        		
        	}
            steps{
                //There might be a warning
            	sh 'docker login -u ${DOCKER_HUB_USR} -p ${DOCKER_HUB_PSW}'
                sh "docker push zarniaung7/selenium"
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}